# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b711a2c28a6ad7f5461615799ebdf8a1ec6d1b60eb83ac6ff8ce15a84408353665cd51aa5c010f71e6e595793df5025660691f9f170b2e1cd4c79ad02f7737c

test:
  secret_key_base: 62b8c4181d91dd3d391a3d23b7ea3429d608d4d878935fb4013272b8eaeb64926b7a93275bde78878e46a33623c0c868e15bab86cde514aebafa1b80fdccd18f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
